<?php
namespace app\index\controller;

use think\Controller;
use app\index\model;
use think\Request;

class Auth extends Controller
{

    protected $input = null;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->input = json_decode(file_get_contents('php://input'), true);
    }

    public function json($body, $errcode = 0, $errmsg = 'ok') {
        $body['errcode'] = $errcode;
        $body['errmsg'] = $errmsg;
        return json_encode($body);
    }

    public function signin() {

        $username = input('username');
        $password = input('password');

        if(strlen($username) < 5 || strlen($password) < 5)
            return $this->fetch();

        if($username || $password) {
            $user = model\Admin::where('username', $username)->find();
            if ($user && $user->password == sha1($password)) {
                session('id', $user->id);
                return $this->redirect('/');
            }
        }

        return $this->fetch();
    }

    public function signout() {
        session('id', 0);
        return $this->redirect('/');
    }
}
